### PR TITLE
Updated Folder Structure

### LINKED ISSUE #14: Fix the folder structure
To much files are in the root that can also be in folders.

### PR DESCRIPTION
**Pull request by VikramNagwal**
fixes #14 

**What does this PR do?**
This pull request has been created to update the folder structure of this project.

screenshots:
image

### CODE REVIEW

**Comment by alexvz901** [comment]
The folders look great, thankyou. Did you check if the program still works? For example the link stylesheet from index.html needs to be changed.

**Review by alexvz901 — CHANGES_REQUESTED** [review]
The code needs to be changed so all the links to other files still work.

**Comment by alexvz901** [comment]
unfortunately this code still does not work. I think now the problem is with app.py not server index.html.
Maybe it's a better to test the code. You can do that with python3 app.py

**Comment by VikramNagwal** [comment]
image

It's working.

**Pull request merged**
